ktor:
  development: true
  deployment:
    port: "$PORT:8080"
#    sslPort: "$PORT:8443"
  application:
    modules:
      - at.gleb.ApplicationKt.module
  mongodb:
    #development db url
    db_url: "$MONGO_DB_URL:mongodb+srv://user:MtPnHISuBTFwRKxM@cluster0.k6waabw.mongodb.net/?retryWrites=true&w=majority"
    db_name: "$MONGO_DB_NAME:dev_review_magic"

  settings:
    dev: "$DEV:0"

  jwt:
    secret: "$JWT_SECRET:saAWEdfwef_sdfew32354"
    issuer: "$JWT_ISSUER:http://0.0.0.0:8080/"
    audience: "$JWT_AUDIENCE:http://0.0.0.0:8080/hello"
    realm: "$JWT_REALM:Access to client console"
  logback:
    file: "logback.xml"

#  security:
#    ssl:
#      keyStore: test.jks
#      keyAlias: testkey
#      keyStorePassword: foobar
#      privateKeyPassword: foobar

